#Task 1: Once you store the MongoDB database, use Python to access. This part can be done using PyMongo. 

##Setting up MongoClient and fetching data

In [ ]:
from pymongo import MongoClient
client = MongoClient()

In [ ]:
def get_database():
    from pymongo import MongoClient
    import pymongo

    # Provide the mongodb atlas url to connect python to mongodb using pymongo
    CONNECTION_STRING = "mongodb://abisht1:96365963@cluster0-shard-00-00.cninn.mongodb.net:27017,cluster0-shard-00-01.cninn.mongodb.net:27017,cluster0-shard-00-02.cninn.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-dhm2wp-shard-0&authSource=admin&retryWrites=true&w=majority"

    # Create a connection using MongoClient. You can import MongoClient or use pymongo.MongoClient
    from pymongo import MongoClient
    client = MongoClient(CONNECTION_STRING)

    # Create the database for our example (we will use the same database throughout the tutorial
    return client['Skytrax']
    
# This is added so that many files can reuse the function get_database()
if __name__ == "__main__":    
    
    # Get the database
    dbname = get_database()

In [ ]:
# Get the database using the method we defined in pymongo_test_insert file 
dbname = get_database()

# Create a new collection
collection_name = dbname["airline_reviews"]

item_details = collection_name.find()

In [ ]:
from pandas import DataFrame
# convert the dictionary objects to dataframe
df_data = DataFrame(collection_name.find())
df_to_neo = df_data
# see the magic
print(df_data)

                            _id  ...        authorname
0      58994af79bf56223b02ab85b  ...   Moam Ben-Shalom
1      58994af99bf56223b02ab85c  ...           A Aamir
2      58994af99bf56223b02ab85d  ...          A Abbado
3      58994af99bf56223b02ab85e  ...          A Acosta
4      58994af99bf56223b02ab85f  ...          A Acosta
...                         ...  ...               ...
41391  58994b179bf56223b02b5a02  ...   Zulkhairul Naim
41392  58994b179bf56223b02b5a05  ...     Zumot Ghassan
41393  58994b179bf56223b02b5a08  ...   Zuzana Daridova
41394  58994b179bf56223b02b5a0b  ...   Zuzana Daridova
41395  58994b179bf56223b02b5a0e  ...   Zuzana Daridova

[41396 rows x 17 columns]


In [ ]:
df_data = df_data[['reviewcontent','recommended']]

In [ ]:
df_data['reviewcontent'] = df_data['reviewcontent'].apply(lambda x:x.lower())
df_data['reviewcontent']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


0        flight was half-full. i had the whole row to m...
1        we have travelled to pakistan many times on pi...
2        sq947 and sq378 aug 19 2014. dps-sin and sin-m...
3        lax-nrt 777-300er. fa's stop to pick up every ...
4        i wasn't sure about this airline when booking ...
                               ...                        
41391    od 1235 on 25 dec. short flight from kota bhar...
41392    mel-kul-pvg return. this is my first trip with...
41393    i was impressed with luxair. my flights were o...
41394    luxembourg - london city return. on a route wh...
41395    how come that every time i call luxair informa...
Name: reviewcontent, Length: 41396, dtype: object

In [ ]:
reviewcontent_list = df_data['reviewcontent']
recommended_list = df_data['recommended']

In [ ]:
len(reviewcontent_list) , len(recommended_list)  

(41396, 41396)

#Task 2: Retrieve customer reviews from the database, and develop sentiment analysis of reviews.

## Stage 1: Text Preprocessing

###Word tokenize

In [ ]:
import nltk
nltk.download('punkt')
from nltk import tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [ ]:
sent_tokenize_list =  [] 
for reviewcontent in reviewcontent_list:
     sent_tokenize_list.append(tokenize.sent_tokenize(reviewcontent))

In [ ]:
word_tokenize_list =   [tokenize.word_tokenize(reviewcontent) for reviewcontent in reviewcontent_list]

In [ ]:
type(sent_tokenize_list), len(sent_tokenize_list)

(list, 41396)

###Remove punctuations 

In [ ]:
from string import punctuation
list_punct = list(punctuation)
print(list_punct)

['!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', ':', ';', '<', '=', '>', '?', '@', '[', '\\', ']', '^', '_', '`', '{', '|', '}', '~']


In [ ]:
def drop_punct(input_tokens):
    return [token for token in input_tokens if token not in list_punct]

In [ ]:
txt_words_nopunct_list = [drop_punct(sent) for sent in word_tokenize_list]
print(txt_words_nopunct_list)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [ ]:
txt_words_nopunct_list[:1]

[['flight',
  'was',
  'half-full',
  'i',
  'had',
  'the',
  'whole',
  'row',
  'to',
  'myself',
  'the',
  'flight',
  'took',
  'of',
  'on',
  'time',
  'and',
  'one',
  'hour',
  'later',
  'the',
  'service',
  'started',
  'i',
  'could',
  'choose',
  '2',
  'drinks',
  'the',
  'meals',
  'service',
  'had',
  'two',
  'choices',
  '1',
  'meat',
  'ball',
  'with',
  'couscous',
  'salad',
  'and',
  'chocolate',
  'cake',
  '2',
  'tuna',
  'salad',
  'some',
  'fruits',
  'and',
  'a',
  'honey',
  'cake',
  'after',
  'the',
  'meal',
  'service',
  'the',
  'lights',
  'inside',
  'the',
  'cabin',
  'were',
  'turned',
  'off',
  'every',
  'hour',
  'one',
  'of',
  'the',
  'cabin',
  'crew',
  'members',
  'came',
  'around',
  'with',
  'water',
  'during',
  'the',
  'whole',
  'flight',
  'there',
  'was',
  'juice',
  'available',
  'in',
  'the',
  'rear',
  'galley',
  'two',
  'hours',
  'before',
  'landing',
  'the',
  'cabin',
  'crew',
  'gave',
  'us',

### Removing stop words

In [ ]:
import nltk
nltk.download("stopwords")
from nltk.corpus import stopwords
list_stop = stopwords.words("english")
len(list_stop)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


179

In [ ]:
def drop_stop(input_tokens):
    return [token for token in input_tokens if token not in list_stop]

In [ ]:
txt_words_nostop_list = [drop_stop(sent) for sent in txt_words_nopunct_list]

### Stemming

In [ ]:
from nltk.stem import PorterStemmer

In [ ]:
stemmer_p = PorterStemmer()

In [ ]:
txt_words_stem = [[stemmer_p.stem(token) for token in sent] for sent in txt_words_nostop_list]

In [ ]:
from gensim.models import word2vec

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(token_pattern=r'\b\w+\b')

In [ ]:
df_data = df_data[['reviewcontent','recommended']]

In [ ]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras import regularizers

max_words = 5000
max_len = 200

tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(txt_words_stem)
sequences = tokenizer.texts_to_sequences(txt_words_stem)
review_content_processed = pad_sequences(sequences, maxlen=max_len)
print(review_content_processed)

[[   0    0    0 ...    5  108    3]
 [   0    0    0 ...  112   44    5]
 [   0    0    0 ...  141 2070  151]
 ...
 [   0    0    0 ...   11  974    1]
 [   0    0    0 ...  733  269  560]
 [   0    0    0 ...  126  106  950]]


In [ ]:
len(review_content_processed)

41396

In [ ]:
y = df_data['recommended']

In [ ]:
len(y)

41396

## Stage 2: Machine Learning

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(review_content_processed,y,test_size=0.2)

In [ ]:
from tensorflow.keras import preprocessing
maxlen = 200
X_train = preprocessing.sequence.pad_sequences(X_train, maxlen=maxlen)
X_test = preprocessing.sequence.pad_sequences(X_test, maxlen=maxlen)

In [ ]:
import numpy as np
import tensorflow as tf

np.random.seed(42)
tf.random.set_seed(42)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Flatten, Dense, Embedding, SpatialDropout1D, Dropout

In [ ]:
model_rnn = Sequential()

In [ ]:
vocab_size = 8000
model_rnn.add(Embedding(vocab_size, output_dim=32))
model_rnn.add(SpatialDropout1D(0.4))

In [ ]:
model_rnn.add(SimpleRNN(32))

In [ ]:
model_rnn.add(Dropout(0.4))

In [ ]:
model_rnn.add(Dense(1, activation='sigmoid'))

In [ ]:
model_rnn.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [ ]:
model_rnn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 32)          256000    
                                                                 
 spatial_dropout1d (SpatialD  (None, None, 32)         0         
 ropout1D)                                                       
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                2080      
                                                                 
 dropout (Dropout)           (None, 32)                0         
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 258,113
Trainable params: 258,113
Non-trainable params: 0
__________________________________________________

In [ ]:
history_rnn = model_rnn.fit(X_train, y_train, batch_size=128, validation_split=0.2, epochs = 10)

Epoch 1/10
207/207 [==============================] - 18s 80ms/step - loss: 0.4690 - accuracy: 0.7849 - val_loss: 0.3753 - val_accuracy: 0.8514
Epoch 2/10
207/207 [==============================] - 14s 67ms/step - loss: 0.3419 - accuracy: 0.8673 - val_loss: 0.3608 - val_accuracy: 0.8536
Epoch 3/10
207/207 [==============================] - 14s 68ms/step - loss: 0.3124 - accuracy: 0.8831 - val_loss: 0.3431 - val_accuracy: 0.8724
Epoch 4/10
207/207 [==============================] - 14s 66ms/step - loss: 0.2990 - accuracy: 0.8886 - val_loss: 0.3298 - val_accuracy: 0.8729
Epoch 5/10
207/207 [==============================] - 14s 67ms/step - loss: 0.2858 - accuracy: 0.8957 - val_loss: 0.3286 - val_accuracy: 0.8688
Epoch 6/10
207/207 [==============================] - 14s 66ms/step - loss: 0.2708 - accuracy: 0.9025 - val_loss: 0.3313 - val_accuracy: 0.8729
Epoch 7/10
207/207 [==============================] - 14s 68ms/step - loss: 0.2581 - accuracy: 0.9059 - val_loss: 0.3449 - val_accuracy:

In [ ]:
#y_test_pred = model_rnn.predict_classes(X_test)
y_test_pred = (model_rnn.predict(X_test) > 0.5).astype("int32")
y_test_pred

array([[1],
       [0],
       [0],
       ...,
       [1],
       [1],
       [0]], dtype=int32)

#Task 3: Construct a rating network between authors and the airline companies that they rated. Such rating network captures who rated which airline companies. Construct this network in Neo4j.

## Stage 1: Exporting to Neo4j via csv

In [ ]:
df_to_neo= df_to_neo.dropna(how="all")

In [ ]:
len(df_to_neo)

41396

In [ ]:
df_to_neo.to_csv("airline_reviews.csv")